# Generated by Django 4.1.2 on 2022-10-29 05:33

from django.db import migrations

from django.contrib.auth.models import User
from django.contrib.auth.models import Group

from datetime import datetime, timedelta
import time

def beginning(apps, schema_editor):
    
    # Суперпользователь id-1
    user = User.objects.create_superuser(username='root',
    email='avc291022@mail.ru',
    password='SsNn5678+-@')
    print("Суперпользователь создан")
    
    # Группа менеджеров
    managers = Group.objects.get_or_create(name = 'Managers')
    managers = Group.objects.get(name='Managers')
    print("Группа менеджеров создана")
    
    # Пользователь с ролью менеджера id2
    user = User.objects.create_user(username='manager', password='Ss0066+-', email='manager@mail.ru', first_name='Менеджер', last_name='')
    managers.user_set.add(user)
    print("Менеджер добавлен в группу менеджеров")

    # Простые пользователи (заявители) id3-12
    user = User.objects.create_user(username='user1', password='Uu0066+-', email='user1@mail.ru', first_name='Дина', last_name='Мусина')
    user = User.objects.create_user(username='user2', password='Uu0066+-', email='user2@mail.ru', first_name='Адия', last_name='Жунусова')
    user = User.objects.create_user(username='user3', password='Uu0066+-', email='user3@mail.ru', first_name='Айнура', last_name='Кенина')
    user = User.objects.create_user(username='user4', password='Uu0066+-', email='user4@mail.ru', first_name='Рустем', last_name='Какимов')
    user = User.objects.create_user(username='user5', password='Uu0066+-', email='user5@mail.ru', first_name='Алишер', last_name='Кабдуалиев')
    user = User.objects.create_user(username='user6', password='Uu0066+-', email='user6@mail.ru', first_name='Бауржан', last_name='Арыкбаев')
    user = User.objects.create_user(username='user7', password='Uu0066+-', email='user7@mail.ru', first_name='Алишер', last_name='Танатаров')
    user = User.objects.create_user(username='user8', password='Uu0066+-', email='user8@mail.ru', first_name='Мерует', last_name='Искакова')
    user = User.objects.create_user(username='user9', password='Uu0066+-', email='user9@mail.ru', first_name='Ольга', last_name='Муравьева')
    user = User.objects.create_user(username='user10', password='Uu0066+-', email='user10@mail.ru', first_name='Ақжарқын', last_name='Сансызбаева')
    print("Созданы простые пользователи")
        
    ##### Новости #####
    News = apps.get_model("cutaway", "News")
    
    news = News()
    news.daten = '2022-07-20 00:00:00'
    news.title = 'Подготовка к производственной практике на ПНХЗ студентов КБТУ'
    news.details = """С целью взращивания квалифицированных кадров в области автоматизации технологических процессов, AVC GROUP привлекает студентов КБТУ, АУНИГ и APEC PETROTECHNIC специальности “АВТОМАТИЗАЦИЯ И УПРАВЛЕНИЕ”, “ХИМИЧЕСКАЯ ИНЖЕНЕРИЯ” к прохождению производственной практики.\n 
В период с 11 по 15 июля в головном офисе AVC Group г.Алматы, первая группа студентов КБТУ начали подготовку к своей первой производственной практике на реальном нефтехимическом заводе. Квалифицированные специалисты AVC Group, которые стали для студентов 4го курса кураторами, провели ознакомление со структурой и производственными процессами предприятия ПНХЗ, приглашенный спикер прочитал лекцию «Теоретические основы физики и химии», ознакомление и введение в практический базовый инжиниринг, прошли практические занятия по системам подготовки проб, а также, практическое задание по моделированию технологического процесса.\n
В рамках подготовки, в обязательном порядке, студенты прошли следующие курсы: • «Обучение по промышленной безопасности для допуска на установки»; • «Обучение по пожарно- техническому минимуму для допуска на установки».\n
Успешно сдали экзамены и получили соответствующие допуски на производство. С 18 по 22 июля их ожидает полное погружение в производственную среду на территории ПНХЗ."""
    news.photo = 'images/news1.jpeg' 
    news.save()
    
    
    news = News()
    news.daten = '2022-07-20 00:00:00'
    news.title = 'Тренинг управления проектами на основе стандарта PMI® PMBOK для сотрудников AVC GROUP'
    news.details =  """В связи с повсеместным внедрением автоматизации бизнес-процессов Компании, в период с 13 июня по 4 июля 2022 года основной состав сотрудников, участвующие в планировании и реализации проектов, прошли базовый курс по Управлению проектами на основе стандарта PMI® PMBOK.\n
Это интенсивный обучающий курс, который в структурированной форме дает базовые знания о современных подходах к управлению проектами и о самом применяемом в мире стандарте по проектному управлению – PMI® PMBOK® Guide (Project Management Body of Knowledge Guide – Руководство к своду знаний по управлению проектами). """
    news.photo = 'images/news2.jpeg' 
    news.save()
    
    news = News()
    news.daten = '2022-07-25 00:00:00'
    news.title = 'Производственная практика на ПНХЗ'
    news.details = """После недели подготовки к производственной практике в головном офисе AVC Group в г.Алматы, и получения всех необходимых допусков на производственные объекты, студенты КБТУ прибыли в г.Павлодар для прохождения производственной практики на территории Павлодарского Нефтехимического Завода.\n 
Цель практики является закрепление и углубление обучающимся теоретических знаний и приобретение им практических навыков и компетенций в сфере профессиональной деятельности.\n
В первую очередь, студенты прошли необходимый курс Техники безопасности на ПНХЗ, после получения пропусков, необходимых средств индивидуальной защиты и спецодежды, была организована обзорная экскурсия по заводу, а также, посещение музея."""
    news.photo = 'images/news3.jpeg' 
    news.save()
    
    news = News()
    news.daten = '2022-08-24 00:00:00'
    news.title = 'AVC Group приняли участие в качестве спонсора Международного шахматного фестиваля в г.Атырау'
    news.details = """Целями проведения турнира являются популяризация и развитие шахмат как вида спорта в Казахстане, пропаганда здорового образа жизни, а также повышение мастерства молодых спортсменов и поиск юных дарований. В соревнованиях приняли участие около 300 любителей шахмат, в числе которых известные международные гроссмейстеры и международные мастера из 9 стран - помимо Казахстана, это США, Нидерланды, Литва, Украина, Таджикистан, Узбекистан, Беларусь и Россия.\n
24 августа состоялось закрытие Международного фестиваля шахмат в г. Атырау. Обладателями медалей, дипломов либо денежных призов в итоге стали более 80 участников фестиваля. Среди них международные гроссмейстеры, юные шахматисты и ветераны."""
    news.photo = 'images/news4.jpeg' 
    news.save()
    
    news = News()
    news.daten = '2022-09-26 00:00:00'
    news.title = 'Алматы Марафон 2022. Сотрудники AVC Group приняли участие в корпоративном забеге'
    news.details = """Часть сотрудников в течении четырех месяцев под кураторством профессионального тренера по бегу, регулярно тренировались и готовились к марафону на разные дистанции, в том числе и к эстафете Экиден.\n
Команда AVC Group в эстафете ЭКИДЕН заняла 12е место из 62 команд. Показав отличный результат, слаженность команды и результат тренировок.\n
У команды AVC Group была отличная поддержка со стороны сотрудников головного офиса, которые пришли в качестве болельщиков."""
    news.photo = 'images/news5.jpeg' 
    news.save()
    
    news = News()
    news.daten = '2022-09-30 00:00:00'
    news.title = 'AVC Group приняли участие в KIOGE 2022'
    news.details = """В рамках KIOGE участники представили новейшие технологические, инжиниринговые и программные разработки для нефтегазодобывающих предприятий от ведущих добывающих, нефтегазовых и нефтесервисных компаний. В экспозиции были представлены 13 направлений нефтегазовой отрасли, включая геологию, геофизику, цифровизацию, неразрушающий контроль, инжиниринговые решения, развитие инфраструктуры и так далее.\n
AVC Group представила и презентовала гостям стенда свои основные направления: - EPC проекты, такие как "Строительство установки производства битума" и "Строительство MEROX - установка очистки сжиженных углеводородных газов"; - Автоматизированные системы мониторинга эмиссий; - демонстрация услуги AVC Lens, которая позволяет осуществлять онлайн техническое обслуживание и аудит оборудование с участием зарубежных партнеров;\n
На стенде Компании работали специалисты всех направлений и подразделений, а также, были проведены переговоры и встречи с настоящими и потенциальными партнерами. Наш стенд отличился ярким дизайном, демонстрацией наших проектов посредством 3Д голограммами и большим количеством посетителей."""
    news.photo = 'images/news6.jpeg' 
    news.save()
    
    news = News()
    news.daten = '2022-10-05 00:00:00'
    news.title = 'Футбольная команда «AVC Group», участвует в регулярном первенстве города Атырау «SME League».'
    news.details = """Данный турнир проводится 2 раза в год, весна-осень, наша команда участвует второй год. Турнир разделен на две группы первая лига и высшая лига, наш коллектив выступает в первой лиге, который состоит из 12 команд, победители этой подгруппы получат возможность перехода в высшую лигу, где играют титулованные футбольные коллективы города Атырау.\n
В целом футбольная команда «AVC Group» на этом турнире в своей подгруппе считаются одними из фаворитов, так наш коллектив в первом туре обыграл команду «Altynsarin» со счетом 7:0, второй тур так же закончился в нашу пользу 4:0.\n
2 октября 2022г. ФК «AVC Group» сыграла свой очередной тур и вновь показали свое мастерство, обыграв команду «Dame Qurylys Group» со счетом 8:0. Таким образом в корзине нашей команды 9 очков и промежуточное первое место после трёх туров.\n
Руководство компании «AVC Group» на регулярной основе оказывает поддержку и выделяет средства для подготовки и участия в турнире, такие как закуп инвентаря, футбольной формы, регулярные тренировки и прочее."""
    news.photo = 'images/news7.jpeg' 
    news.save()
    
    ##### Сообщения #####
    Message = apps.get_model("cutaway", "Message")
    
    message = Message()
    message.datem = datetime.now() - timedelta(minutes=10)
    message.sender_id = 3
    message.recipient_id = 4
    message.details = 'Привет, Адия' 
    message.save()

    time.sleep(1)
    
    message = Message()
    message.datem = datetime.now() - timedelta(minutes=9)
    message.sender_id = 4
    message.recipient_id = 3
    message.details = 'Привет, Дина!' 
    message.save()

    time.sleep(1)
    
    message = Message()
    message.datem = datetime.now() - timedelta(minutes=8)
    message.sender_id = 3
    message.recipient_id = 4
    message.details = 'Как дела?' 
    message.save()

    time.sleep(1)

    message = Message()
    message.datem = datetime.now() - timedelta(minutes=7)
    message.sender_id = 4
    message.recipient_id = 3
    message.details = 'Спасибо, все хорошо. Сами как?' 
    message.save()

    time.sleep(1)
    
    message = Message()
    message.datem = datetime.now() - timedelta(minutes=6)
    message.sender_id = 3
    message.recipient_id = 5
    message.details = 'Привет, Айнура' 
    message.save()

    time.sleep(1)
    
    message = Message()
    message.datem = datetime.now() - timedelta(minutes=5)
    message.sender_id = 5
    message.recipient_id = 3
    message.details = 'Приветcтвую Вас, Дина' 
    message.save()

    time.sleep(1)
    
    message = Message()
    message.datem = datetime.now() - timedelta(minutes=4)
    message.sender_id = 3
    message.recipient_id = 5
    message.details = 'Как дела, ребята подъехали?' 
    message.save()

    time.sleep(1)

    message = Message()
    message.datem = datetime.now() - timedelta(minutes=3)
    message.sender_id = 5
    message.recipient_id = 3
    message.details = 'Пока нет, ждем' 
    message.save()

    time.sleep(1)

    message = Message()
    message.datem = datetime.now() - timedelta(minutes=3)
    message.sender_id = 6
    message.recipient_id = 7
    message.details = 'Добрый день, Алишер' 
    message.save()

    time.sleep(1)

    message = Message()
    message.datem = datetime.now() - timedelta(minutes=3)
    message.sender_id = 7
    message.recipient_id = 6
    message.details = 'Добрый день, Рустем' 
    message.save()

    ##### Форум #####
    ##### Раздел форума #####
    Board = apps.get_model("cutaway", "Board")
    ##### Тема форума #####
    Topic = apps.get_model("cutaway", "Topic")
    ##### Сообщение (POST) для форума #####
    Post = apps.get_model("cutaway", "Post")
    ##### Тема №1 форума #####
    board = Board()
    board.name = 'Поставка оборудования и техники'
    board.description = 'Раздел посявящен поставке оборудования и техники' 
    board.save()

    topic = Topic()
    topic.subject = 'Проблемы при перемещении оборудования через границу РК'
    topic.last_updated = datetime.now() 
    topic.board = board
    topic.starter_id = 3
    topic.views = 1
    topic.save()

    time.sleep(1)

    post = Post()
    post.message = 'Как правильно оформить документы?'
    post.topic = topic
    post.created_at = datetime.now() - timedelta(minutes=2)
    #post.updated_at = datetime.now()
    post.created_by_id = 4
    #post.updated_by_id = 4
    post.save()

    time.sleep(1)

    post = Post()
    post.message = 'Обязательно надо накладная!'
    post.topic = topic
    post.created_at = datetime.now() - timedelta(minutes=1)
    #post.updated_at = datetime.datetime.now()
    post.created_by_id = 5
    #post.updated_by_id = 1
    post.save()

    time.sleep(1)

    post = Post()
    post.message = 'Также может понадобится счет-фактура'
    post.topic = topic
    post.created_at = datetime.now() - timedelta(minutes=0)
    #post.updated_at = datetime.datetime.now()
    post.created_by_id = 7
    #post.updated_by_id = 7
    post.save()

    time.sleep(1)

    ##### Тема №2 форума #####
    board = Board()
    board.name = 'Ремонт и обслуживание техники'
    board.description = 'Раздел посявящен ремонту и обслуживанию техники' 
    board.save()

    topic = Topic()
    topic.subject = 'Ремонт центробежных насосов'
    topic.last_updated = datetime.now() 
    topic.board = board
    topic.starter_id = 5
    topic.views = 1
    topic.save()

    time.sleep(1)
    
    post = Post()
    post.message = 'Если кто-нибудь сталкивался с ремонтом центробежных насосов, буду признательна за любую информацию по вопросу'
    post.topic = topic
    post.created_at = datetime.now() - timedelta(minutes=4)
    #post.updated_at = datetime.now()
    post.created_by_id = 6
    #post.updated_by_id = 6
    post.save()

    time.sleep(1)
    
    post = Post()
    post.message = '"Ремонт оборудования объектов Госжилкоммунхоза", начиная с ЖР5-1165'
    post.topic = topic
    post.created_at = datetime.now() - timedelta(minutes=3)
    #post.updated_at = datetime.now()
    post.created_by_id = 6
    #post.updated_by_id = 6
    post.save()

    time.sleep(1)
    
    topic = Topic()
    topic.subject = 'Ремонт компрессоров'
    topic.last_updated = datetime.now() 
    topic.board = board
    topic.starter_id = 5
    topic.views = 1
    topic.save()

    time.sleep(1)
    
    post = Post()
    post.message = 'Один поршень вроде нормально крутится а второй клинит.вроде немного провернулся один раз треть оборота но очень туго. это можно вылечить?'
    post.topic = topic
    post.created_at = datetime.now() - timedelta(minutes=4)
    #post.updated_at = datetime.now()
    post.created_by_id = 7
    #post.updated_by_id = 7
    post.save()

    time.sleep(1)
    
    post = Post()
    post.message = 'Если снять вал я думаю вал вытащится из железки на которой стоят крутятся поршн'
    post.topic = topic
    post.created_at = datetime.now() - timedelta(minutes=4)
    #post.updated_at = datetime.now()
    post.created_by_id = 8
    #post.updated_by_id = 8
    post.save()

    ##### Тема №3 форума #####
    board = Board()
    board.name = 'Эксплуатация техники'
    board.description = 'Раздел посявящен эксплуатации техники' 
    board.save()

    topic = Topic()
    topic.subject = 'Эксплуатация запорной арматуры - задвижек'
    topic.last_updated = datetime.now() 
    topic.board = board
    topic.starter_id = 5
    topic.views = 1
    topic.save()

    time.sleep(1)
    
    post = Post()
    post.message = 'Нужна Ваша помощь в вопросе запорной арматуры - задвижек. Не могу понять каковы именно достоинства и недостатки различных видов задвижек: 1) клиновой / параллельной 2) жесткий клин / упругий клин / двойной 3) параллельный двухдисковый / шиберный'
    post.topic = topic
    post.created_at = datetime.now() - timedelta(minutes=4)
    #post.updated_at = datetime.now()
    post.created_by_id = 9
    #post.updated_by_id = 9
    post.save()

    time.sleep(1)
    
    post = Post()
    post.message = 'Все решает заказчик. Вот пару лет назад объявили о развитии СПГ и его транспортировку морем, так в нашей стране и начали осваивать криогенную и судовую арматуру с энтузиазмом. Пожалуй на сегодня это самые перспективные направления. Ну и конечно серийная арматура, на общепром, по отзывам многих руководителей предприятий, сегодня становится выгоднее производить в России, чем закупать в Китае и перепродавать. По крайней мере серийную арматуру, к которой в том числе относятся задвижки и затворы крупных диаметров'
    post.topic = topic
    post.created_at = datetime.now() - timedelta(minutes=3)
    #post.updated_at = datetime.now()
    post.created_by_id = 10
    #post.updated_by_id = 10
    post.save()

    ##### Тема №4 форума #####
    board = Board()
    board.name = 'Вопрос специалисту'
    board.description = 'Задавайте свой вопрос специалисту' 
    board.save()

    print("Разделы форума добавлены")
    print("Темы форума добавлены")
    print("Сообщения форума добавлены")
    
class Migration(migrations.Migration):

    dependencies = [
        ('cutaway', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(beginning),       
        #migrations.RunSQL("""CREATE VIEW view_message AS
        #                SELECT message.id, message.datem, message.sender_id, s.username AS sender_username, s.first_name AS sender_first_name, s.last_name AS sender_last_name,
        #                message.recipient_id, r.username AS recipient_username, r.first_name AS recipient_first_name, r.last_name AS recipient_last_name, message.details,
        #                (SELECT strftime('%d.%m.%Y %H:%M:%S', m2.datem)|| ' ' || s2.username  || '-' || r2.username || ': ' || m2.details FROM message m2  LEFT JOIN auth_user s2 ON message.sender_id=s2.id LEFT JOIN auth_user r2 ON message.recipient_id=r2.id
        #                WHERE  ((m2.sender_id = message.sender_id) AND (m2.recipient_id = message.recipient_id)) OR ((m2.sender_id = message.recipient_id) AND(m2.recipient_id = message.sender_id)) ORDER BY m2.datem DESC LIMIT 1) AS last_message
        #                FROM message LEFT JOIN auth_user s ON message.sender_id=s.id LEFT JOIN auth_user r ON message.recipient_id=r.id"""),        
        migrations.RunSQL("""CREATE VIEW view_message AS
                        SELECT message.id, message.datem, message.sender_id, s.username AS sender_username, s.first_name AS sender_first_name, s.last_name AS sender_last_name,
                        message.recipient_id, r.username AS recipient_username, r.first_name AS recipient_first_name, r.last_name AS recipient_last_name, message.details                        
                        FROM message LEFT JOIN auth_user s ON message.sender_id=s.id LEFT JOIN auth_user r ON message.recipient_id=r.id"""),      
        migrations.RunSQL("""CREATE VIEW view_user_last_message AS
                        SELECT auth_user.id, auth_user.is_superuser, auth_user.username, auth_user.first_name, auth_user.last_name,
                        (SELECT m1.recipient_id FROM message m1 WHERE m1.sender_id=auth_user.id ORDER BY m1.datem DESC LIMIT 1) AS last_send_id,
                        (SELECT strftime('%d.%m.%Y %H:%M:%S', m1.datem)|| ': ' || m1.details FROM message m1 WHERE m1.sender_id=auth_user.id ORDER BY m1.datem DESC LIMIT 1) AS last_send_message,
                        (SELECT m2.sender_id FROM message m2 WHERE m2.recipient_id=auth_user.id ORDER BY m2.datem DESC LIMIT 1) AS last_recipient_id,
                        (SELECT strftime('%d.%m.%Y %H:%M:%S', m2.datem)|| ': ' || m2.details FROM message m2 WHERE m2.recipient_id=auth_user.id ORDER BY m2.datem DESC LIMIT 1) AS last_recipient_message
                        FROM auth_user """), 

    ]


